// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6nQ5Lv4KdzjgXLxsFIBbVTaM9-YUTLFk',
    appId: '1:542967426668:web:123b348b2ec90e83c27249',
    messagingSenderId: '542967426668',
    projectId: 'bus-project-4347d',
    authDomain: 'bus-project-4347d.firebaseapp.com',
    storageBucket: 'bus-project-4347d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCkYq6GiKQ21P2jYpD0OLR2Spy5VGi1uQ',
    appId: '1:542967426668:android:9393d5aee59278b9c27249',
    messagingSenderId: '542967426668',
    projectId: 'bus-project-4347d',
    storageBucket: 'bus-project-4347d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA9mwA4oqyGI9Qjkyk00Zn5Ke-45wIpEo',
    appId: '1:542967426668:ios:bafa99dd7a125dbac27249',
    messagingSenderId: '542967426668',
    projectId: 'bus-project-4347d',
    storageBucket: 'bus-project-4347d.appspot.com',
    iosClientId: '542967426668-dm22fs1blg47um95srkk8iidbna5007j.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigoTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA9mwA4oqyGI9Qjkyk00Zn5Ke-45wIpEo',
    appId: '1:542967426668:ios:bafa99dd7a125dbac27249',
    messagingSenderId: '542967426668',
    projectId: 'bus-project-4347d',
    storageBucket: 'bus-project-4347d.appspot.com',
    iosClientId: '542967426668-dm22fs1blg47um95srkk8iidbna5007j.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigoTracker',
  );
}
